# Permalinks
permalink:           pretty

# Setup
title:               Playground for learning data analysis
tagline:             by Dorota
url:                 http://dorotamierzwa.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Dorota Mierzwa
  url:               https://twitter.com/DorotaMierzwa
  email:             mierzwa.dorota@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist